[package]
name = "cargo-deb"
license = "MIT"
authors = ["Michael Aaron Murphy <mmstickman@gmail.com>", "Kornel Lesiński <kornel@geekhood.net>"]
categories = ["command-line-utilities", "development-tools::cargo-plugins", "development-tools::build-utils"]
description = "Cargo subcommand that generates Debian packages"
documentation = "https://github.com/mmstick/cargo-deb#readme"
homepage = "https://github.com/mmstick/cargo-deb"
keywords = ["cargo", "subcommand", "deb", "debian", "package"]
repository = "https://github.com/mmstick/cargo-deb"
readme = "README.md"
version = "1.1.2"

[badges]
travis-ci = { repository = "mmstick/cargo-deb" }

[package.metadata.deb]
maintainer = "Michael Aaron Murphy <mmstickman@gmail.com>"
copyright = "2016-2017, Michael Aaron Murphy, Kornel Lesiński"
license-file = ["LICENSE", "5"]
extended-description = """\
A simple subcommand for the Cargo package manager for \
building Debian packages from Rust projects."""
depends = "$auto"
section = "utility"
priority = "optional"
assets = [
    ["target/release/cargo-deb", "usr/bin/", "755"],
    ["README.md", "usr/share/doc/cargo-deb/README", "644"],
]

[dependencies]
file = "1.1.1"
getopts = "0.2.14"
libc = "0.2.15"
md5 = "0.3.5"
quick-error = "1.2.0"
rust-lzma = { version = "0.2.1", optional = true }
serde = "1.0.11"
serde_derive = "1.0.11"
serde_json = "1.0.2"
tar = "0.4.13"
toml = "0.4.4"
zopfli = "0.3.0"

[features]
default = ["lzma"]
lzma = ["rust-lzma"]

[profile.release]
lto = true
opt-level = 3

