[package]
name = "cargo-deb"
version = "0.0.1"
license = "MIT"
authors = ["Michael Aaron Murphy <mmstickman@gmail.com>"]
description = "Cargo subcommand that generates Debian packages"
keywords = [ "cargo", "subcommand", "deb" ]
repository = "https://github.com/mmstick/cargo-deb"

[package.metadata.deb]
maintainer = "Michael Aaron Murphy <mmstickman@gmail.com>"
copyright = "2016, Michael Aaron Murphy <mmstickman@gmail.com>"
license_file = ["LICENSE", "4"]
extended_description = """\
A simple subcommand for the Cargo package manager for \
building Debian packages from Rust projects."""
depends = "$auto"
section = "utility"
priority = "optional"
assets = [
    ["target/release/cargo-deb", "usr/bin/", "755"],
    ["README.md", "usr/share/doc/cargo-deb/README", "644"],
]

[dependencies]
rustc-serialize = "0.3.19"
toml = "0.1.28"
libc = "0.2.12"
tar = { git = "https://github.com/mmstick/tar-rs" }
rust-lzma = "0.2.1"
zopfli = { git = "https://github.com/carols10cents/zopfli" }
