[package]
name = "cargo-deb"
license = "MIT"
authors = ["Michael Aaron Murphy <mmstickman@gmail.com>", "Kornel Lesiński <kornel@geekhood.net>"]
categories = ["command-line-utilities", "development-tools::cargo-plugins", "development-tools::build-utils"]
description = "Cargo subcommand that generates Debian packages"
keywords = ["cargo", "subcommand", "deb", "debian"]
repository = "https://github.com/mmstick/cargo-deb"
version = "0.1.0"

[package.metadata.deb]
maintainer = "Michael Aaron Murphy <mmstickman@gmail.com>"
copyright = "2016, Michael Aaron Murphy <mmstickman@gmail.com>"
license-file = ["LICENSE", "4"]
extended-description = """\
A simple subcommand for the Cargo package manager for \
building Debian packages from Rust projects."""
depends = "$auto"
section = "utility"
priority = "optional"
assets = [
    ["target/release/cargo-deb", "usr/bin/", "755"],
    ["README.md", "usr/share/doc/cargo-deb/README", "644"],
]

[dependencies]
itertools = "0.4.17"
libc = "0.2.15"
md5 = "0.3.5"
rust-lzma = "0.2.1"
tar = { git = "https://github.com/mmstick/tar-rs" }
serde = "1.0.11"
serde_derive = "1.0.11"
serde_json = "1.0.2"
toml = "0.4.4"
zopfli = "0.3.0"

[profile.release]
lto = true
opt-level = 3

